### ISSUE TITLE
[runwhen-local-feedback] Bug: Developers can't list namespaces in OpenShift

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/runwhen-local#1]
**Observation** 
Tested on OKD 4.13, OpenShift 4.12.3 (CodeReadyContainers).

As a cluster admin there were no issues in either environment.

As a developer with access to only a few namespaces I ran into RBAC issues because OpenShift prefers projects instead of namespaces by default. The standard user / developer RBAC does not include permissions to list namespaces resulting in a fatal exception. (OpenShift creates an identical Project when a Namespace is created and vice-versa)

Note: Make sure the developer context is not in the kubeconfig or generation will fail with an exception.

```
Internal Server Error: /run/
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/workspace-builder/prodgraph/views.py", line 105, in post
    raise e
  File "/workspace-builder/prodgraph/views.py", line 98, in post
    component.run_func(context)
  File "/workspace-builder/indexers/kubeapi.py", line 113, in index
    ret = core_api_client.list_namespace()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 14721, in list_namespace
    return self.list_namespace_with_http_info(**kwargs)  # noqa: E501
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 14828, in list_namespace_with_http_info
    return self.api_client.call_api(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/kubernetes/client/rest.py", line 241, in GET
    return self.request("GET", url,
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/kubernetes/client/rest.py", line 235, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '3b8d84a0-b522-47ed-bfdc-7a4d6324110a', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '19a3dc24-ba00-43cc-bd97-8679fcc8ca83', 'X-Kubernetes-Pf-Prioritylevel-Uid': '78b618f3-7def-4784-8cf4-75416a1bd9d0', 'Date': 'Thu, 01 Jun 2023 05:12:03 GMT', 'Content-Length': '264'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"developer\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}


[01/Jun/2023 05:13:00] "POST /run/ HTTP/1.1" 500 145
```

**Possible Suggestions**
If running against OpenShift we should try listing projects if namespaces can't be listed.
```
  apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/sa.scc.mcs: s0:c26,c5
      openshift.io/sa.scc.supplemental-groups: 1000660000/10000
      openshift.io/sa.scc.uid-range: 1000660000/10000
    creationTimestamp: "2023-06-01T04:49:55Z"
    labels:
      kubernetes.io/metadata.name: test
      pod-security.kubernetes.io/audit: restricted
      pod-security.kubernetes.io/audit-version: v1.24
      pod-security.kubernetes.io/warn: restricted
      pod-security.kubernetes.io/warn-version: v1.24
    name: test
    resourceVersion: "57784"
    uid: ef083331-7581-4b50-8c0c-e3b80c810fcd
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
```

**Comment by stewartshea** [comment]
This should now be resolved in this version (https://github.com/runwhen-contrib/runwhen-local/pkgs/container/runwhen-local/99624808?tag=main-6c8a27f0), tested against our demo ocp cluster with a standard developer view permissions to the default namespace with a simple app. 

![image](https://github.com/runwhen-contrib/runwhen-local/assets/18314168/044a114c-f643-415f-9de3-4826afd3a8d2)
