### ISSUE TITLE
[runwhen-local-feedback] OpenShift error: sqlite3.OperationalError: unable to open database file  The above exception was the direct cause of the following exception:

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/runwhen-local#251]
**Observation** 
Attempting to deploy this directly into OpenShift causes the following error: 
```
Starting up neo4j
Waiting a bit before starting workspace builder REST server
WARNING -  Config value 'build': Unrecognised configuration name: build
WARNING -  Config value 'dev_addr': The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Documentation built in 0.46 seconds
INFO    -  [18:02:55] Watching paths for changes: 'cheat-sheet-docs/docs', 'cheat-sheet-docs/mkdocs.yml'
INFO    -  [18:02:55] Serving on http://0.0.0.0:8081/
Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed before the database is started for the first time.
2023-08-17 18:02:59.849+0000 INFO  Starting...
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 180, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file
```

**Possible Suggestions**
The UID assigned from OpenShift would likely be the root cause here; we need to modify the entrypoint to support the random UIDs assigned from OpenShift to add them into the runwhen group for it to have access to the correct files. This will require testing in an OCP cluster.

**Comment by stewartshea** [comment]
Reproduce with docker by specifying a different uid: 

```
docker run --name RunWhenLocal -p 8081:8081 -v $workdir/shared:/shared  -d --user 10001 runwhen-local:test

Starting workspace builder REST server
2023-08-18 12:41:31.814+0000 INFO  Starting...
Performing system checks...

System check identified no issues (0 silenced).
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 180, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file
```

**Comment by stewartshea** [comment]
so 0.1.11 fixes the error encountered above, but we are now experiencing this, which is a bit odd - related to an SSL verification error when performing a git clone of the github troubleshooting command repo. I'm not quite sure why this would be openshift specific? I'm not seeing it in local executions of the container .
```
Starting cheat sheet rendering...
Failed to clone the repository due to: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/runwhen-contrib/rw-cli-codecollection /workspace-builder/rw-cli-codecollection-cache
  stderr: 'Cloning into '/workspace-builder/rw-cli-codecollection-cache'...
fatal: unable to access 'https://github.com/runwhen-contrib/rw-cli-codecollection/': server certificate verification failed. CAfile: none CRLfile: none
'
Failed to clone the repository due to: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/runwhen-contrib/rw-cli-codecollection.git /workspace-builder/rw-cli-codecollection-cache
  stderr: 'Cloning into '/workspace-builder/rw-cli-codecollection-cache'...
fatal: unable to access 'https://github.com/runwhen-contrib/rw-cli-codecollection.git/': server certificate verification failed. CAfile: none CRLfile: none

```

**Comment by stewartshea** [comment]
I actually think that last problem is isolated to our single-node ocp lab cluster, as the pod itself is lacking any form of outbound network access. This should not be related to the application.

**Comment by stewartshea** [comment]
@jewzaam let me know if you have better luck with [0.1.11](https://github.com/runwhen-contrib/runwhen-local/pkgs/container/runwhen-local/119992992?tag=latest)
